/**
 *  Action list for application
 */

export const LOADED_ADVENTURE = "LOADED_ADVENTURE";
export const LOADED_ALL_ADVENTURES = "LOADED_ALL_ADVENTURES";
export const ADDED_ADVENTURE = "ADDED_ADVENTURE";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const DELETED_ADVENTURE = "DELETED_ADVENTURE";
export const EDITED_ADVENTURE = "EDITED_ADVENTURE";
export const REGISTERED_USER = "REGISTERED_USER";
export const ADDED_MESSAGE = "ADDED_MESSAGE";
export const REMOVED_MESSAGES = "REMOVED_MESSAGES";